### ISSUE TITLE
Update for Gatsby v5

### ISSUE THREAD

**Issue by acocheo** [cedricdelpoux/gatsby-remark-gifs#21]
https://github.com/cedricdelpoux/gatsby-remark-gifs/blob/1ca9b4d0053ca46c3851ba137cbd813b555f8885/package.json#L37
Pleas add also Gatsby v5:
`"gatsby": "^3.0.0 || ^4.0.0" ` or `gatsby": ">3.0.0"`

I tried the plugin on a v5 project ( installing it with *npm i --legacy-peer-deps*) and it works correctly

**Comment by cedricdelpoux** [comment]
Published in v`1.2.0`
